# Generated by Django 4.2.3 on 2024-04-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_certifyinginstitution_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(
                related_name="certificates", to="projects.profile"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="timestamp",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="certifyinginstitution",
            name="url",
            field=models.URLField(max_length=50),
        ),
    ]
